apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Seyi-OjoArgoCD-ToDoApp/.git
    targetRevision: HEAD
    path: 'ARGOCD-TODOAPP/nginx'
    helm:
      valueFiles:
      - '../helm-values/nginx-values.yaml'
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true