replicaCount: 2
image:
  repository: nginx
  tag: "latest"
service:
  type: LoadBalancer
  port: 80
  targetPort: 80

config:
  enabled: true
  config: |
    server {
      listen 80;
      location / {
        proxy_pass http://todo-app:5000;  # Forward requests to the Python app
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }